language: node_js
node_js:
  - "12"

services:
  - docker

branches:
  only:
    - main
    - feed
    - user

stages:
  - name: build_feed
    if: type = pull && head_branch = "feed"

jobs:
  include:
    - stage: build_feed
      name: building_feed
      script:
        - echo "Building an image for the feed service"
        - docker build -t alkaj/udagram-feed:$TRAVIS_BUILD_NUMBER ./feed
        - echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
        - docker push alkaj/udagram-feed:$TRAVIS_BUILD_NUMBER
