language: node_js
node_js:
  - "12"

services:
  - docker

branches:
  only:
    - main
    - feed
    - user

deploy:
  provider: script
  script:
    if: $TRAVIS_PULL_REQUEST_BRANCH = "user"
    env: B=user

    if: $TRAVIS_PULL_REQUEST_BRANCH = "feed"
    env: B=feed