language: node_js
node_js:
  - "12"

services:
  - docker

branches:
  only:
    - main
    - feed
    - user

stages:
  - name: build_feed
    if: type = pull && head_branch = "feed"

jobs:
  include:
    - stage: build_feed
      name: building_feed
      script:
        - echo "Building feed branch for a merge to main"
