apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-front
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: udagram-front
          image: alkaj/udagram-front
          ports:
            - containerPort: 80
