apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: udagram-user
          image: alkaj/udagram-user
          ports:
            - containerPort: 8080
